---
# the alaveteli repo to use
# Note: this is the alaveteli app which is normally fetched from
# https://github.com/mysociety/alaveteli/
# but this setting allows us to use a fork and branch
# for hotfixes or customisations
alaveteli_repo: "https://github.com/okfnfr/alaveteli/"
# the branch, tag or commit ref to checkout. Defaults to master
alaveteli_commit: fix_external_command_path

user_support_emails: demandes@madada.fr

db_name_production: alaveteli_production
db_name_test: alaveteli_test
db_user_password: "{{ lookup('env', 'DB_USER_PASSWORD_PRODUCTION') }}"

# this one is in vault.yml, encrypted
rails_secret_key_base: "{{ vault_rails_secret_key_base }}"

site_domain: madada.fr

# hostname of the server
server_name: dadaprod1

# these env vars come from travis secret variables
incoming_email_secret: "{{ lookup('env', 'INCOMING_EMAIL_SECRET_PRODUCTION') }}"

emergency_admin_password: "{{ lookup('env', 'EMERGENCY_ADMIN_PASSWORD_PRODUCTION') }}"

# the recaptcha keys come from https://www.google.com/recaptcha/admin/site/345908267/settings
# the site key can be public, as it appears in the HTML page sent to user browsers
recaptcha_site_key: 6LfLmp0UAAAAAKCIr6oiwnT773NGA8wHsTihHVTq
# the secret key must be set as a secret env var in travis
recaptcha_secret_key: "{{ lookup('env', 'RECAPTCHA_SECRET_KEY_PRODUCTION') }}"

# send all requests to public bodies to this email instead
# useful for staging, set to empty string in production
override_all_public_body_emails: dada@where.tf

# change the prefix for staging/production
# to limit confusion
incoming_email_short_prefix: dada
incoming_email_prefix: "{{ incoming_email_short_prefix }}+"

# git branch in theme repo to use for the site
# the production site should use master
theme_branch: master

# folder where exim will write incoming emails
raw_emails_location: files/raw_emails

# api token to download the translations
# Any account that has access to them should work
transifex_token: "{{ lookup('env', 'TRANSIFEX_TOKEN') }}"

# we want search engines to index this site
do_not_crawl: false

# backup on exoscale block storage
# these come from travis env vars
backup_storage_access_key: "{{ lookup('env', 'BACKUP_STORAGE_ACCESS_KEY') }}"
backup_storage_secret_key: "{{ lookup('env', 'BACKUP_STORAGE_SECRET_KEY') }}"

db_backup_walg_envdir: /etc/wal-g.d/env
db_backup_archive_mode: "on"
db_backup_archive_command: "/usr/bin/envdir {{ db_backup_walg_envdir }} /usr/local/bin/wal-g wal-push %p"
db_backup_storage_endpoint: "https://sos-ch-gva-2.exo.io"
db_backup_storage_prefix: "s3://madada-db-backup"
